apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadgopn7860-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadgopn7860-tenant-component
    app.kubernetes.io/part-of: loadgopn7860-tenant-app
  name: loadgopn7860-tenant-component
  namespace: loadgopn7860-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadgopn7860-tenant-component
    weight: null
status: {}
